"""shared constants"""
TYPE_BOOLEAN = 16
TYPE_INT8 = 20
TYPE_INT2 = 21
TYPE_INT4 = 23
TYPE_TEXT = 25
TYPE_FLOAT4 = 700
TYPE_FLOAT8 = 701
TYPE_DATE = 1082
TYPE_TIME = 1083
TYPE_TIMESTAMP = 1114
TYPE_NUMERIC = 1700

TYPE_TIMESTAMPTZ = 1184  # 2019-05-26 16:43:26.949167+00
TYPE_DATE = 1082  # 2019-05-26
TYPE_TIMEZ = 1266  # 16:43:26.949167+00

TAG_PASSWORD = 'p'
TAG_AUTHENTICATION = 'R'
TAG_PARAMETER_STATUS = 'S'
TAG_BACKEND_KEY_DATA = 'K'
TAG_READY_FOR_QUERY = 'Z'
TAG_QUERY = 'Q'
TAG_ROW_DESCRIPTION = 'T'
TAG_DATA_ROW = 'D'
TAG_COMMAND_COMPLETE = 'C'
TAG_COMMAND_ERROR = 'E'

NAME_PARAMETER_STATUS = 'parameter_status'
NAME_BACKEND_KEY_DATA = 'backend_key_data'
NAME_READY_FOR_QUERY = 'ready_for_query'
NAME_ROW_DESCRIPTION = 'row_description'
NAME_DATA_ROW = 'data_row'
NAME_COMMAND_COMPLETE = 'command_complete'
NAME_COMMAND_ERROR = 'error'

AUTHENTICATION_OK = 0
AUTHENTICATION_MD5_PASSWORD = 5

NAME_AUTHENTICATION_OK = 'authentication_ok'
NAME_AUTHENTICATION_MD5_PASSWORD = 'authentication_md5'
